### ISSUE TITLE
introduction.xhtml tweaks

### ISSUE THREAD

**Issue by acabal** [gwcoffey/rabindranath-tagore_gitanjali#5]
- Remove leading `<b>` tag from intro, and remove from `local.css` if not in use anywhere else
- Sections headed with `<h3>` should be wrapped in `<section epub:type="subchapter">`
- Body tag must be `z3998:non-fiction`

**Comment by gwcoffey** [comment]
Thanks for the close review! Quick question on this one: Should I remove the <b> tags (title case first word) from the individual poems as well? I was just copying the source scans here, but I'm not married to it.

**Comment by acabal** [comment]
Yes, you can remove them.  Typically we don't include that kind of styling.
